version: '3.3'

volumes:
  jackett_config:
  jackett_downloads:

  qbittorrent_config:
  qbittorrent_downloads:

  sonarr_config:
  sonarr_tv:

  radarr_config:
  radarr_movies:

  jellyfin_config:
  jellyfin_cache:


services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - CAPTCHA_SOLVER=harvester
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - 9117:9117
    depends_on:
      - flaresolverr
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=6888
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6888:6888
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022
    volumes:
      - sonarr_config:/config
      - sonarr_tv:/tv
      - qbittorrent_downloads:/downloads
    ports:
      - 8989:8989
    depends_on:
      - jackett
      - qbittorrent
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - qbittorrent_downloads:/downloads
    ports:
      - 7878:7878
    depends_on:
      - jackett
      - qbittorrent
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - sonarr_tv:/tv
      - radarr_movies:/movies
    ports:
      - 8096:8096
    restart: unless-stopped
